---
title: "Data607 Project 2"
author: "Talha Muhammad"
date: "October 23, 2016"
output: html_document
---
```{r setup, warning=FALSE,message=FALSE}
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
```

# Dataset 1: Loan Data From Lending Tree
       
This analysis looks at the 2012-2013 loans data from Lending Tree. 

```{r filepath, include=FALSE}
datadir=file.path("C://Users//talha//Documents//Training//Datasets//Financial//Lendingclub//")
filename=file.path(datadir,"LoanStats3b.csv")
```


```{r cleandata, warning=FALSE,message=FALSE}
lendingdata<-read.csv(filename,header=TRUE,stringsAsFactors=FALSE,skip=1)
#dataset can be located at
lendingdata$url<-NULL
lendingdata$desc<-NULL
#clean up zip code data
lendingdata$zip_code<-str_replace(lendingdata$zip_code,"xx","")
#clean interest rate data
lendingdata$int_rate<-as.numeric(str_replace(lendingdata$int_rate,"%",""))
summary(lendingdata$int_rate)
lendingdata$revol_util<-as.numeric(str_replace(lendingdata$revol_util,"%",""))
summary(lendingdata$revol_util)

# clean loan term
lendingdata$term<-as.numeric(str_replace(lendingdata$term,"months",""))
summary(lendingdata$term)
# clean emp_length
lendingdata$emp_length<-str_trim(str_replace(lendingdata$emp_length,"years",""),"both")
lendingdata$emp_length<-str_replace(lendingdata$emp_length,"\\+","")
lendingdata$emp_length<-as.numeric(lendingdata$emp_length)
lendingdata<-mutate(lendingdata,emp_lencat=ifelse(emp_length<1,"<1",ifelse(((emp_length>=1)&(emp_length<3)),"1-3",ifelse(((emp_length>=3)&(emp_length<5)),"3-5",ifelse(((emp_length>=5)&(emp_length<=9)),"5-9",ifelse(emp_length>9,"10+",NA))))))
#process dates
lendingdata<-rename(lendingdata,cr_line=earliest_cr_line)
lendingdata$cr_line<-str_c("01-",lendingdata$cr_line)
lendingdata$cr_line<-as.Date(lendingdata$cr_line,format="%d-%b-%Y")

lendingdata$last_pymnt_d<-str_c("01-",lendingdata$last_pymnt_d)
lendingdata$last_pymnt_d<-as.Date(lendingdata$last_pymnt_d,format="%d-%b-%Y")
 
lendingdata$issue_d<-str_c("01-",lendingdata$issue_d)
lendingdata$issue_d<-as.Date(lendingdata$issue_d,format="%d-%b-%Y")

#credit history
lendingdata<-mutate(lendingdata,cr_hist=difftime(issue_d,cr_line,units=c("weeks")))
lendingdata$cr_hist<-lendingdata$cr_hist/52  #convert to years
lendingdata$last_pymnt_d<-format(lendingdata$last_pymnt_d,"%b-%Y")
lendingdata$issue_d<-format(lendingdata$issue_d,"%b-%Y") 
lendingdata$cr_line<-format(lendingdata$cr_line,"%b-%Y")
#convert to factors
lendingdata$application_type<-as.factor(lendingdata$application_type)
lendingdata$home_ownership<-as.factor(lendingdata$home_ownership)
lendingdata$verification_status<-as.factor(lendingdata$verification_status)
lendingdata$loan_status<-as.factor(lendingdata$loan_status)
#select variables of interest
lendingdata<-select(lendingdata,one_of(c("id","member_id","addr_state","loan_amnt","int_rate","term","installment","emp_length","home_ownership","annual_inc","cr_hist","issue_d","cr_line","last_pymnt_d","verification_status","loan_status","emp_length","emp_lencat")))
head(lendingdata)

```
       
       
Various summaries and charts of the clean data are presented below:        
```{r summary_analysis}
#summary of loans by state
su_total<-lendingdata %>% 
  group_by(addr_state) %>% 
  summarize(total_loans=sum(loan_amnt/1000000))
su_total<-su_total[!(su_total$addr_state==""),]
ggplot(su_total,aes(x=addr_state,y=total_loans))+geom_bar(stat="identity")+ylab("Total Loans (in Millions)")+theme(axis.text.x=element_text(size=8,angle=90))+ xlab("US State")+ggtitle("Total Loans by State (in Millions)")

a<-subset(lendingdata,((addr_state=="NY")|(addr_state=="NJ")|(addr_state=="CT")),select=c(addr_state,home_ownership,int_rate))
y <- ggplot(a, aes(y=int_rate, x=home_ownership)) + geom_boxplot(aes(color=home_ownership))
y+facet_grid(~addr_state)+ylab("Interest Rate %")+xlab("Home Ownership")+theme(legend.position="top",axis.text.x=element_text(size=5))+ggtitle("Interest Rates by Home Ownership in Tristate Area")

su_intrate<-lendingdata %>% 
  group_by(addr_state) %>% 
  summarize(avg_irate=mean(int_rate))
su_intrate<-su_intrate[!(su_intrate$addr_state==""),]
ggplot(su_intrate,aes(x=addr_state,y=avg_irate))+geom_point()+ylab("Interest Rate %")+xlab("US State")+ggtitle("Average Interest Rate by State")+theme(axis.text.x=element_text(size=8,angle=90))

b<-subset(lendingdata,((addr_state=="NY")|(addr_state=="NJ")),select=c(addr_state,emp_lencat,int_rate))
ggplot(b, aes(y=int_rate, x=emp_lencat)) + geom_boxplot(aes(color=emp_lencat))+ylab("Interest Rate %")+xlab("Employment Length")

lendingdata$annual_inc<-lendingdata$annual_inc/1000
z<-ggplot(lendingdata,aes(x=annual_inc,y=int_rate))+geom_point(aes(color=emp_lencat))+ylab("Interest Rate %")+xlab("Annual Income in Ths dollars")+ggtitle("Loan Interest Rates by Employment Category and Income")
z+facet_grid(~emp_lencat)

p<-ggplot(lendingdata,aes(x=cr_hist,y=int_rate))+geom_point(aes(color=emp_lencat))+ylab("Interest Rate %")+xlab("Credit History in Years")+ggtitle("Loan Interest Rates by Credit History and Employment")+scale_x_continuous(breaks=seq(0,75,15))
p+facet_grid(~emp_lencat)
```

# Dataset 2: Citibike Usage Data
```{r citibike filepath, warning=FALSE,message=FALSE}
datadir=file.path("C://Users//talha//Documents//Training//Datasets//Transportation//Citibike//")
filename1=file.path(datadir,"201509-citibike-tripdata.csv")
filename2=file.path(datadir,"201609-citibike-tripdata.csv")
```


```{r citibike cleandata, warning=FALSE,message=FALSE}
# dataset can be located at
#load and merge the files
bikedata<-read.csv(filename1,header=TRUE,stringsAsFactors=FALSE)
sep16<-read.csv(filename2,header=TRUE,stringsAsFactors=FALSE)
head(bikedata)
head(sep16)
bikedata<-bind_rows(bikedata,sep16)
sep16<-NULL
#clean & classify date data
bikedata$starttime<-strptime(bikedata$starttime,"%m/%d/%Y %H:%M:%S")
bikedata$starttime<-as.POSIXct(bikedata$starttime,format="%m/%d/%Y %H:%M:%S")
bikedata$stday=format(as.POSIXct(bikedata$starttime, format="%m/%d/%Y %H:%M:%S"), format="%u")
bikedata$stdate=format(as.POSIXct(bikedata$starttime, format="%m/%d/%Y %H:%M:%S"), format="%F")
bikedata$sthour=format(as.POSIXct(bikedata$starttime, format="%m/%d/%Y %H:%M:%S"), format="%H")
bikedata$year=format(as.POSIXct(bikedata$starttime, format="%m/%d/%Y %H:%M:%S"), format="%Y")
bikedata$stoptime<-strptime(bikedata$stoptime,"%m/%d/%Y %H:%M:%S")
bikedata$stoptime<-as.POSIXct(bikedata$stoptime,format="%m/%d/%Y %H:%M:%S")
bikedata$endday=format(as.POSIXct(bikedata$stoptime, format="%m/%d/%Y %H:%M:%S"), format="%u")
bikedata$enddate=format(as.POSIXct(bikedata$stoptime, format="%m/%d/%Y %H:%M:%S"), format="%F")
bikedata$endhour=format(as.POSIXct(bikedata$stoptime, format="%m/%d/%Y %H:%M:%S"), format="%H")
#trip duration in minutes
bikedata$tripduration<-bikedata$tripduration/60
#age of users
bikedata$year<-as.integer(bikedata$year)
bikedata<-mutate(bikedata,age=year-birth.year)
#flag for start end location
bikedata<-mutate(bikedata,sameloc=ifelse(start.station.id==end.station.id,1,0))
#age category
bikedata<-mutate(bikedata,age_cat=ifelse(age<=21,"<21",ifelse((age>21 & age<=29),"21-29",ifelse((age>29&age<=39),"30-39",ifelse((age>39&age<=49),"40-49",ifelse(age>50,"50+",NA))))))
#weekend flag 
bikedata<-mutate(bikedata,weekend=ifelse(stday<=5,0,1))
#gender 
bikedata$gender<-as.factor(bikedata$gender)
bikedata$gender<-factor(bikedata$gender,labels=c("unknown","male","female"))
head(bikedata)
```


```{r citibike summary}
#create summary of users by age
subike_age<-bikedata %>% 
  group_by(year,age_cat) %>% 
  count()
subike_age<-subike_age[!(is.na(subike_age$age_cat)),]
subike_age$n<-subike_age$n/1000
z<-ggplot(subike_age,aes(x=age_cat,y=n, color=age_cat,fill=age_cat))+geom_bar(stat="identity")+ylab("Users in Thousands")+theme(axis.text.x=element_text(size=8,angle=90))+ xlab("Age Category")+ggtitle("Users in Sept 2015 vs Sept 2016")
z+facet_grid(~year)
#create summary of users by sex type
subike_sex<-bikedata %>% 
  group_by(year,gender) %>% 
  count()
subike_sex$n<-subike_sex$n/1000
z<-ggplot(subike_sex,aes(x=gender,y=n, color=gender,fill=gender))+geom_bar(stat="identity")+ylab("Users in Thousands")+theme(axis.text.x=element_text(size=8,angle=90))+ xlab("User Sex")+ggtitle("Users in Sept 2015 vs Sept 2016")
z+facet_grid(~year)
#summary of users by subscriber type
subike_sub<-bikedata %>% 
  group_by(year,usertype) %>% 
  count()
subike_sub$n<-subike_sub$n/1000
z<-ggplot(subike_sub,aes(x=usertype,y=n, color=usertype,fill=usertype))+geom_bar(stat="identity")+ylab("Users in Thousands")+theme(axis.text.x=element_text(size=8,angle=90))+ xlab("User Type")+ggtitle("Users in Sept 2015 vs Sept 2016")
z+facet_grid(~year)
```

# Dataset 3: Chicago Crime Data Set
```{r Chicago crime filepath, warning=FALSE,message=FALSE}
datadir=file.path("C://Users//talha//Documents//Training//Datasets//Crime//Chicago//")
filename1=file.path(datadir,"Crimes.csv")
```

```{r Crime datacleaning}
crimedata<-read.csv(filename1,header=TRUE,stringsAsFactors=FALSE)
#rename variables
crimedata<-rename(crimedata,id=ï..ID,casenum=Case.Number,crimedate=Date,primary=Primary.Type,area=Community.Area,loc_type=Location.Description,fbicode=FBI.Code,x_loc=X.Coordinate,y_loc=Y.Coordinate,last_update=Updated.On)
#change case of column names
names(crimedata)<-tolower(names(crimedata))
#change to NULL
crimedata$x<-NULL
crimedata<-separate(crimedata,location,c("lat","long"),sep=",")
crimedata$lat<-transmute(crimedata,lat=ifelse(lat=="",NA,lat))
head(crimedata)
```