---
title: "Week 10 Assignment: Document Classification"
author: "Talha Muhammad"
date: "November 6, 2016"
output: html_document
---

## Overview Spam Email Filtering


```{r packages, warning=FALSE, warning=FALSE}
library(RCurl)
library(XML)
library(stringr)
library(tm)
library(RTextTools)
```

```{r Loadfiles}
#training files
ehamfiles_train<-list.files("easy_ham_20021010")
hhamfiles_train<-list.files("hard_ham_20021010")
spamfiles_train<-list.files("spam_20021010")
#test files
ehamfiles_test<-list.files("easy_ham_20030228")
hhamfiles_test<-list.files("hard_ham_20030228")
spamfiles_test<-list.files("spam_20030228")

```

```{r define function}
#write function
#takes as argument an directory, listoffiles and an input set
makecorpus<-function(dir,flist,input)
{
  for(i in 1:length(flist))
  {
    if(i==1){
     corp=readLines(file.path(dir,flist[i]))
     corp<-str_replace_all(corp,"[[___]]+","")
     corp<-str_replace_all(corp,"[[***]]+","")
     corp<-str_trim(corp,side=c("both"))
     corp<-str_to_lower(corp)
     corp<-unlist(corp)

    #remove dates 
    corp<-str_replace_all(corp,"\\d{2}\\s[:alpha:]{3}\\s\\d{4}","")
    #remove times
    corp<-str_replace_all(corp,"\\s?(\\d{2}\\:\\d{2}\\:\\d{2})(\\s[-|+]\\d{4})?","")
    #remove IP addresses
    corp<-str_replace_all(corp,"\\[\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\]","")
    #collapse readlines
    corp<-str_c(corp,collapse=" ")
    corp<-VectorSource(corp)
    corp<-Corpus(corp)

} else {

     tmp=readLines(file.path(dir,flist[i]))
     tmp<-str_replace_all(tmp,"[[___]]+","")
     tmp<-str_replace_all(tmp,"[[***]]+","")
     tmp<-str_trim(tmp,side=c("both"))
     tmp<-str_to_lower(tmp)
     tmp<-unlist(tmp)

    #remove dates 
    tmp<-str_replace_all(tmp,"\\d{2}\\s[:alpha:]{3}\\s\\d{4}","")
    #remove times
    tmp<-str_replace_all(tmp,"\\s?(\\d{2}\\:\\d{2}\\:\\d{2})(\\s[-|+]\\d{4})?","")
    #remove IP addresses
    tmp<-str_replace_all(tmp,"\\[\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\]","")
    #collapse readlines
    tmp<-str_c(tmp,collapse=" ")
    tmp<-VectorSource(tmp)
    tmp<-Corpus(tmp)
    corp<-c(corp,tmp)
    }
    meta(corp[[i]],"ID")<-i
    meta(corp[[i]],"ham")<-input
    }
 
  return(corp)
}
###end function

```

```{r analysis}
#load all the corpus'
eham<-makecorpus("easy_ham_20021010",ehamfiles_train,1)  
hham<-makecorpus("hard_ham_20021010",hhamfiles_train,1)
spam<-makecorpus("spam_20021010",spamfiles_train,0)

eham_test<-makecorpus("easy_ham_20030228",ehamfiles_test,1)
hham_test<-makecorpus("hard_ham_20030228",hhamfiles_test,1)
spam_test<-makecorpus("spam_20030228",spamfiles_test,0)
#combine all the files
#final corpus
finalcorpus<-c(eham,hham,spam,eham_test,hham_test,spam_test)
#develop term document matrix
tdm<-TermDocumentMatrix(finalcorpus)
tdm<-removeSparseTerms(tdm,1-(10/length(finalcorpus)))

#develop container
ham_spam<-unlist(meta(finalcorpus,type="local",tag="ham"))
N<-length(ham_spam)
tsize<-length(eham)+length(hham)+length(spam)
container<-create_container(tdm,ham_spam,trainSize= 1:tsize,testSize= 3303:N, virgin=FALSE)
#slot names
slotNames(container)

#different models estimated
#svm_model<-train_model(container,"SVM")
#tree_model<-train_model(container,"TREE")
#boost_model<-train_model(container,"BOOSTING")
#maxent_model<-train_model(container,"MAXENT")

#getting an column error here
#model output
#svm_out<-classify_model(container,svm_model)
#tree_out<-classify_model(contaner,tree_model)
#boost_out<-classify_model(container,boost_model)
#maxtent_out<-classify_model(container,maxent_model)

```